version: '3.2'

services:
  db:
    image: postgres:latest
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
  api:
    image: elongton/recipes_django:v0
    # build: django/.
    command: bash -c "python manage.py makemigrations &&
                      python manage.py migrate &&
                      python setup_webapp.py &&
                      gunicorn recipeApi.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./media_volume:/src/mediafiles
      # - ./backup:/src/backup
    ports:
      - "8000:8000"
    depends_on:
      - db
  angular:
    image: elongton/recipes_angular:v0
    # build: angular/.
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  media_volume: