# Generated by Django 2.2.6 on 2019-10-27 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='base_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Unit'),
        ),
    ]
