# Generated by Django 2.2.6 on 2019-11-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredientlink',
            old_name='notes',
            new_name='ingredient_notes',
        ),
        migrations.AddField(
            model_name='recipeingredientlink',
            name='recipe_notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipeingredientlink',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ri_ingredient', to='api.Ingredient'),
        ),
    ]
