# Generated by Django 2.2.6 on 2019-11-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('world_cuisine', 'World Cuisine'), ('popular_tags', 'Popular Tag'), ('meal_type', 'Meal Type'), ('flavors', 'Flavors'), ('seasonal', 'Seasonal'), ('prep_time', 'Prep Time'), ('dietary_requirements', 'Dietary Requirements')], default='popular', max_length=50),
        ),
    ]
