# Generated by Django 2.2.6 on 2019-10-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unittype',
            old_name='unit_type',
            new_name='name',
        ),
        migrations.AddField(
            model_name='unittype',
            name='symbol',
            field=models.CharField(default='D', max_length=1),
            preserve_default=False,
        ),
    ]
