# Generated by Django 2.2.6 on 2019-11-16 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191116_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredientlink',
            name='recipe_as_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_as_ingredient', to='api.Recipe'),
        ),
    ]
