# Generated by Django 2.2.6 on 2019-11-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recipeingredientlink_recipe_as_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredientlink',
            name='is_recipe_as_ingredient',
            field=models.BooleanField(default=False),
        ),
    ]
