# Generated by Django 2.2.6 on 2019-12-01 23:21

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.file_pk_name),
        ),
        migrations.AlterField(
            model_name='recipetaglink',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.Recipe'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_type',
            field=models.CharField(choices=[('tag_category', 'Tag Category')], default='tag_category', max_length=200),
        ),
    ]
