# Generated by Django 3.0.1 on 2019-12-27 18:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191222_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='shopping_cart',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
