# Generated by Django 2.2.6 on 2019-10-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191016_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredientlink',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
