# Generated by Django 2.2.6 on 2019-12-03 01:02

import api.helpers.storage
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191201_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='user_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.helpers.storage.OverwriteStorage(), upload_to=api.helpers.storage.file_pk_name),
        ),
    ]
