# Generated by Django 2.2.6 on 2019-10-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191026_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unittype',
            name='symbol',
        ),
    ]
