# Generated by Django 2.2.6 on 2019-12-03 01:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191203_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='user_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
