# Generated by Django 2.2.6 on 2019-11-10 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_unittype_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTypeIngredientLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_link', to='api.Ingredient')),
                ('unit_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_link', to='api.UnitType')),
            ],
        ),
    ]
