# Generated by Django 3.0.1 on 2020-01-08 00:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191227_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='meal_planner',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
