# Generated by Django 2.2.6 on 2019-12-03 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191203_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermeta',
            old_name='user_meta',
            new_name='meta',
        ),
        migrations.RemoveField(
            model_name='usermeta',
            name='recently_browsed_tags',
        ),
    ]
