# Generated by Django 2.2.6 on 2019-10-21 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ingredient_baseunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='baseUnit',
            new_name='base_unit',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='unitType',
            new_name='unit_type',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='unitType',
            new_name='unit_type',
        ),
    ]
