# Generated by Django 2.2.6 on 2019-11-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_ingredient_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittypeingredientlink',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_link', to='api.Ingredient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unittypeingredientlink',
            name='unit_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='unit_link', to='api.UnitType'),
            preserve_default=False,
        ),
    ]
