# Generated by Django 2.2.6 on 2019-10-21 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191021_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='base_unit',
        ),
        migrations.AddField(
            model_name='unit',
            name='base_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base', to='api.Unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='multiplier',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
