# Generated by Django 2.2.6 on 2019-10-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='new recipe', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('instructions', models.TextField()),
            ],
        ),
    ]
