# Generated by Django 2.2.6 on 2019-10-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unitType',
            field=models.CharField(choices=[('W', 'Wet'), ('D', 'Dry'), ('P', 'Poultry')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unitType',
            field=models.CharField(choices=[('W', 'Wet'), ('D', 'Dry'), ('P', 'Poultry')], default='D', max_length=1),
        ),
    ]
