# Generated by Django 2.2.6 on 2019-10-07 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191007_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='api.Ingredient')),
                ('recipeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='api.Recipe')),
            ],
        ),
    ]
