# Generated by Django 2.2.6 on 2019-10-08 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recipeingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ri_ingredientId', to='api.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ri_recipeId', to='api.Recipe'),
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rt_recipeId', to='api.Recipe')),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rt_tagId', to='api.Tag')),
            ],
        ),
    ]
