# Generated by Django 2.2.6 on 2019-10-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191012_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='units',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unitType',
            field=models.CharField(choices=[('W', 'Wet'), ('D', 'Dry')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='units',
            name='unitType',
            field=models.CharField(choices=[('W', 'Wet'), ('D', 'Dry')], default='D', max_length=1),
        ),
    ]
