# Generated by Django 2.2.6 on 2019-10-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191013_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredientlink',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.Unit'),
        ),
    ]
