# Generated by Django 2.2.6 on 2019-10-13 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recipeingredientlink_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientlink',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.Unit'),
        ),
    ]
