version: '3.2'

services:
  web:
      restart: always
      build: .
      ports:
        - "80:80"
      volumes:
        - ../media_volume:/usr/share/nginx/media_volume
      networks:
        - custom
      external_links:
        - recipes_angular_1:recipes_angular
        - recipes_api_1:recipes_django

networks:
  custom:
    external: true